apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 574205320701.dkr.ecr.ap-northeast-2.amazonaws.com/project/flask:latest
        ports:
        - containerPort: 5000
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: GEMINI_API_KEY
        - name: TAGO_API_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: TAGO_API_KEY
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: API_KEY
        - name: FLASK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: FLASK_SECRET_KEY
        - name: MYSQL_URI
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: MYSQL_URI
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: "ap-northeast-2"
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: S3_BUCKET
        - name: DYNAMODB_TABLE
          valueFrom:
            secretKeyRef:
              name: flask-secrets
              key: DYNAMODB_TABLE 